// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20231103235738_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.DomainClass.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city_iata_code")
                        .HasColumnType("longtext");

                    b.Property<string>("country_iso2")
                        .HasColumnType("longtext");

                    b.Property<string>("country_name")
                        .HasColumnType("longtext");

                    b.Property<string>("geoname_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gmt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iata_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("icao_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Domain.DomainClass.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("airportname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("flight_date")
                        .HasColumnType("date");

                    b.Property<string>("flight_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Domain.DomainClass.Airport", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Name", "airport_name", b1 =>
                        {
                            b1.Property<int>("AirportId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("airport_name");

                            b1.HasKey("AirportId");

                            b1.ToTable("Airports");

                            b1.WithOwner()
                                .HasForeignKey("AirportId");
                        });

                    b.Navigation("airport_name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
